#!/bin/bash
# Set terminal title before and during execution
printf '\033]0;J-PI\007'

# Prevent zsh precmd/preexec from overriding the title
export DISABLE_AUTO_TITLE="true"

export JPI_SRC="$(cd "$(dirname "$0")/src" && pwd)"
export JBIN="/Applications/j9.8/bin/jconsole"
"$JBIN" "$JPI_SRC/tui_run.ijs"

# Restore title on exit
printf '\033]0;%s\007' "${SHELL##*/}"
